// Replace with any JSONL spec; seed state with an {"op":"add","path":"/state",...} line.
export const specJsonl = String.raw`{"op":"add","path":"/root","value":"products-panel"}
{"op":"add","path":"/state","value":{"productsResponse":{"products":[]},"productsLoading":true,"activeProduct":null,"selectedProduct":null,"selectedProductJson":"","productDialogVisible":false}}
{"op":"add","path":"/elements/products-panel","value":{"type":"Panel","props":{"header":"Product Catalog"},"children":["reload-button","products-loader","products-table","product-dialog"],"on":{"mount":{"action":"fetchData","params":{"url":"https://dummyjson.com/products?limit=0","statePath":"/productsResponse","loadingPath":"/productsLoading"}}}}}
{"op":"add","path":"/elements/reload-button","value":{"type":"Button","props":{"label":"Reload products","icon":"pi pi-refresh","size":"small","outlined":true,"loading":{"$state":"/productsLoading"}},"children":[],"on":{"click":{"action":"fetchData","params":{"url":"https://dummyjson.com/products?limit=0","statePath":"/productsResponse","loadingPath":"/productsLoading"}}}}}
{"op":"add","path":"/elements/products-loader","value":{"type":"ProgressSpinner","props":{"aria-label":"Loading products","style":{"display":"block","margin":"2rem auto"}},"children":[],"visible":{"$state":"/productsLoading"}}}
{"op":"add","path":"/elements/products-table","value":{"type":"DataTable","props":{"value":{"$state":"/productsResponse/products"},"paginator":true,"rows":10,"rowsPerPageOptions":[10,25,50],"stripedRows":true,"showGridlines":true,"removableSort":true,"tableStyle":{"min-width":"60rem"}},"children":["product-title-col","product-category-col","product-brand-col","product-price-col","product-rating-col","product-stock-col","product-status-col","product-details-col"],"visible":{"$state":"/productsLoading","not":true}}}
{"op":"add","path":"/elements/product-title-col","value":{"type":"Column","props":{"field":"title","header":"Product","sortable":true},"children":[]}}
{"op":"add","path":"/elements/product-category-col","value":{"type":"Column","props":{"field":"category","header":"Category","sortable":true},"children":[]}}
{"op":"add","path":"/elements/product-brand-col","value":{"type":"Column","props":{"field":"brand","header":"Brand","sortable":true},"children":[]}}
{"op":"add","path":"/elements/product-price-col","value":{"type":"Column","props":{"field":"price","header":"Price","sortable":true},"children":[]}}
{"op":"add","path":"/elements/product-rating-col","value":{"type":"Column","props":{"field":"rating","header":"Rating","sortable":true},"children":[]}}
{"op":"add","path":"/elements/product-stock-col","value":{"type":"Column","props":{"field":"stock","header":"Stock","sortable":true},"children":[]}}
{"op":"add","path":"/elements/product-status-col","value":{"type":"Column","props":{"field":"availabilityStatus","header":"Availability","sortable":true},"children":[]}}
{"op":"add","path":"/elements/product-details-col","value":{"type":"Column","props":{"header":"Details","rowContextPath":"/activeProduct","style":{"width":"5rem"}},"children":[],"slots":{"body":["product-details-button"]}}}
{"op":"add","path":"/elements/product-details-button","value":{"type":"Button","props":{"icon":"pi pi-eye","rounded":true,"text":true,"severity":"secondary","aria-label":"View product details"},"children":[],"on":{"click":{"action":"showProductDetails","params":{"product":{"$state":"/activeProduct"}}}}}}
{"op":"add","path":"/elements/product-dialog","value":{"type":"Dialog","props":{"header":"Product details","visible":{"$bindState":"/productDialogVisible"},"modal":true,"draggable":false,"style":{"width":"min(50rem, 90vw)"},"breakpoints":{"960px":"75vw","640px":"95vw"}},"children":["product-json-details"]}}
{"op":"add","path":"/elements/product-json-details","value":{"type":"Textarea","props":{"modelValue":{"$state":"/selectedProductJson"},"readonly":true,"autoResize":true,"rows":20,"aria-label":"Complete product details","style":{"width":"100%","font-family":"monospace"}},"children":[]}}`;
